CC = g++
CFLAGS = -Wall -g

main: main.cpp Sprite.cpp Hero.cpp Monster.cpp Inventory.cpp Item.cpp Sword.cpp Armor.cpp
	$(CC) $(CFLAGS) -o main main.cpp Sprite.cpp Hero.cpp Monster.cpp Inventory.cpp Item.cpp Sword.cpp Armor.cpp