CC = g++
CFLAGS = -Wall -g

main: main.cpp osoba.cpp adresa.cpp polozkaFaktury.cpp faktura.cpp
	$(CC) $(CFLAGS) -o main main.cpp osoba.cpp adresa.cpp polozkaFaktury.cpp faktura.cpp

clean:
	rm -f main